apiVersion: 1
datasources:
  - name: WorkforceOps Prometheus
    uid: workforce-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
  - name: WorkforceOps Jaeger
    uid: workforce-jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    editable: false
